In [4]:
import numpy as np
import matplotlib as plt
from scipy.linalg import circulant
# import CSS_builder
from util.CSS_builder import *


ModuleNotFoundError: No module named 'CSS_builder'

In [154]:
# Setup
B_N = 14
B_M = 7
B_n = 7
B_indices = np.array([0, 1, 3])

# Matrix setup
B_c_start = np.zeros(B_n, dtype=int)
B_c_start[B_indices] += 1

In [155]:
# Construct the cyclic perfect difference set matrices

# This is actually the transpose of what I wanted
B_CirculantT = np.array(circulant(B_c_start))
print(B_CirculantT.T)

[[1 1 0 1 0 0 0]
 [0 1 1 0 1 0 0]
 [0 0 1 1 0 1 0]
 [0 0 0 1 1 0 1]
 [1 0 0 0 1 1 0]
 [0 1 0 0 0 1 1]
 [1 0 1 0 0 0 1]]


In [156]:
# Add cyclic perfect difference set matrices together
B_Comp = np.zeros((B_n, 2*B_n), dtype=int)
B_Comp[:,B_n:2*B_n] = B_CirculantT
B_Comp[:,0:B_n] = B_CirculantT.T
print(B_Comp)

[[1 1 0 1 0 0 0 1 0 0 0 1 0 1]
 [0 1 1 0 1 0 0 1 1 0 0 0 1 0]
 [0 0 1 1 0 1 0 0 1 1 0 0 0 1]
 [0 0 0 1 1 0 1 1 0 1 1 0 0 0]
 [1 0 0 0 1 1 0 0 1 0 1 1 0 0]
 [0 1 0 0 0 1 1 0 0 1 0 1 1 0]
 [1 0 1 0 0 0 1 0 0 0 1 0 1 1]]


In [157]:
# Create H_0 to be used to make the A = ( H_0 |  0  ) matrix
#                                       (  0  | H_0 )
B_H_0 = B_Comp[0:B_M,0:B_N]
print(B_H_0)

[[1 1 0 1 0 0 0 1 0 0 0 1 0 1]
 [0 1 1 0 1 0 0 1 1 0 0 0 1 0]
 [0 0 1 1 0 1 0 0 1 1 0 0 0 1]
 [0 0 0 1 1 0 1 1 0 1 1 0 0 0]
 [1 0 0 0 1 1 0 0 1 0 1 1 0 0]
 [0 1 0 0 0 1 1 0 0 1 0 1 1 0]
 [1 0 1 0 0 0 1 0 0 0 1 0 1 1]]


In [158]:
# Construct the parity check matrix

B_PCM = np.zeros((2*B_M, 2*B_N), dtype=int)
B_PCM[0:B_M, 0:B_N] = B_H_0
B_PCM[B_M:2*B_M, B_N:2*B_N] = B_H_0

print(B_PCM)

[[1 1 0 1 0 0 0 1 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 1 0 1 0 0 1 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 1 0 1 0 0 1 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 1 0 1 1 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 1 1 0 0 1 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 1 1 0 0 1 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 1 0 0 0 1 0 0 0 1 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 1 0 0 0 1 0 0 0 1 0 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 1 0 0 1 1 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 1 0 0 1 1 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 1 1 0 1 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 1 0 0 1 0 1 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 1 0 0 1 0 1 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 1 0 0 0 1 0 1 1]]


In [159]:
for i in range(2*B_n):
    for j in range(B_n - (i%B_n) - 1):
        if np.count_nonzero(np.bitwise_and(B_PCM[i], B_PCM[i + j + 1])) != 2:
            print("Error:")
            print(B_PCM[i])
            print(B_PCM[i + j + 1])

In [160]:
B_start = B_starter([0, 1, 3], 7)
B_code = CSS(B.getH())
print(B_code.getPCM())
B_code.checkTP()

TypeError: '<' not supported between instances of 'list' and 'int'