In [1]:
using LDPCDecoders
using Test
using SparseArrays

using Revise
using CairoMakie      # For plotting (incluing tableau diagrams)
using Quantikz        # For drawing quantum circuits
using QuantumClifford # For quantum Clifford circuits
using QuantumClifford.ECC: parity_checks, Steane7, Shor9, naive_syndrome_circuit, faults_matrix, naive_syndrome_circuit, parity_checks, AbstractECC, naive_encoding_circuit, Cleve8, Steane7, Shor9, Perfect5
using LinearAlgebra
using SparseArrays

In [2]:
include("util/CSS_builder.jl")
include("util/QECC_Decoders.jl")
include("util/QECC_Tests.jl")
include("util/pfcircuit_eval.jl")

using .CSS_Builder
using .QECC_Decoders
using .QECC_Tests
using .PauliFrame_Eval

Syndrome: 

Bool[0, 0, 0, 0, 0, 0]
Guess: Bool[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
O: 

Bool[0 0 0 0 0 0 0 0 0 1 0 1 1 0; 0 1 0 1 0 1 0 0 0 0 0 0 0 0]
Guess: Bool[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
Mult: 

[0, 0]
result_Z: [0]
logic synd: Bool[0]
Decoded!


Syndrome: Bool[0, 0, 0, 0, 0, 0]
Guess: Bool[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
O: Bool[0 0 0 0 0 0 0 0 0 1 0 1 1 0; 0 1 0 1 0 1 0 0 0 0 0 0 0 0]
Guess: Bool[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
Mult: [0, 0]
result_Z: [0]
logic synd: Bool[0]
Decoded!
Syndrome: Bool[0, 0, 0, 0, 0, 0]
Guess: Bool[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
O: Bool[0 0 0 0 0 0 0 0 0 1 0 1 1 0; 0 1 0 1 0 1 0 0 0 0 0 0 0 0]
Guess: Bool[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
Mult: [0, 0]
result_Z: [0]
logic synd: Bool[0]
Decoded!


Syndrome: Bool[0, 0, 0, 0, 0, 0]
Guess: Bool[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
O: Bool[0 0 0 0 0 0 0 0 0 1 0 1 1 0; 0 1 0 1 0 1 0 0 0 0 0 0 0 0]
Guess: Bool[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
Mult: [0, 0]
result_Z: [0]
logic synd: Bool[0]
Decoded!
Syndrome: Bool[0, 0, 0, 0, 0, 0]
Guess: Bool[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
O: Bool[0 0 0 0 0 0 0 0 0 1 0 1 1 0; 0 1 0 1 0 1 0 0 0 0 0 0 0 0]
Guess: Bool[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
Mult: [0, 0]
result_Z: [0]
logic synd: Bool[0]
Decoded!
Syndrome: Bool[0, 0, 0, 0, 0, 0]
Guess: Bool[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
O: Bool[0 0 0 0 0 0 0 0 0 1 0 1 1 0; 0 1 0 1 0 1 0 0 0 0 0 0 0 0]
Guess: Bool[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
Mult: [0, 0]
result_Z: [0]
logic synd: Bool[0]
Decoded!


Syndrome: Bool[0, 0, 0, 0, 0, 1]
Guess: Bool[0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0]
O: Bool[0 0 0 0 0 0 0 0 0 1 0 1 1 0; 0 1 0 1 0 1 0 0 0 0 0 0 0 0]
Guess: Bool[0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0]
Mult: [0, 0]
result_Z: [0]
logic synd: Bool[0]
Decoded!
Syndrome: Bool[0, 0, 0, 0, 0, 0]
Guess: Bool[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
O: Bool[0 0 0 0 0 0 0 0 0 1 0 1 1 0; 0 1 0 1 0 1 0 0 0 0 0 0 0 0]
Guess: Bool[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
Mult: [0, 0]
result_Z: [0]
logic synd: Bool[0]
Decoded!
Syndrome: Bool[0, 0, 0, 0, 0, 0]
Guess: Bool[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
O: Bool[0 0 0 0 0 0 0 0 0 1 0 1 1 0; 0 1 0 1 0 1 0 0 0 0 0 0 0 0]
Guess: Bool[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
Mult: [0, 0]
result_Z: [0]
logic synd: Bool[0]
Decoded!


Syndrome: Bool[0, 0, 0, 0, 0, 0]
Guess: Bool[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
O: Bool[0 0 0 0 0 0 0 0 0 1 0 1 1 0; 0 1 0 1 0 1 0 0 0 0 0 0 0 0]
Guess: Bool[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
Mult: [0, 0]
result_Z: [0]
logic synd: Bool[0]
Decoded!
Syndrome: Bool[0, 0, 0, 0, 0, 0]
Guess: Bool[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
O: Bool[0 0 0 0 0 0 0 0 0 1 0 1 1 0; 0 1 0 1 0 1 0 0 0 0 0 0 0 0]
Guess: Bool[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
Mult: [0, 0]
result_Z: [0]
logic synd: Bool[0]
Decoded!
Syndrome: Bool[0, 0, 0, 0, 0, 0]
Guess: Bool[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
O: Bool[0 0 0 0 0 0 0 0 0 1 0 1 1 0; 0 1 0 1 0 1 0 0 0 0 0 0 0 0]
Guess: Bool[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
Mult: [0, 0]
result_Z: [0]
logic synd: Bool[0]
Decoded!


Syndrome: Bool[0, 0, 0, 0, 0, 0]
Guess: Bool[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
O: Bool[0 0 0 0 0 0 0 0 0 1 0 1 1 0; 0 1 0 1 0 1 0 0 0 0 0 0 0 0]
Guess: Bool[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
Mult: [0, 0]
result_Z: [0]
logic synd: Bool[0]
Decoded!
Syndrome: Bool[1, 0, 1, 1, 0, 1]
Guess: Bool[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0]
O: Bool[0 0 0 0 0 0 0 0 0 1 0 1 1 0; 0 1 0 1 0 1 0 0 0 0 0 0 0 0]
Guess: Bool[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0]
Mult: [1, 0]
result_Z: [0]
logic synd: Bool[1]
Syndrome: Bool[0, 0, 0, 0, 0, 0]
Guess: Bool[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
O: Bool[0 0 0 0 0 0 0 0 0 1 0 1 1 0; 0 1 0 1 0 1 0 0 0 0 0 0 0 0]
Guess: Bool[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
Mult: [0, 0]
result_Z: [0]
logic synd: Bool[0]
Decoded!


Syndrome: Bool[0, 0, 0, 0, 0, 0]
Guess: Bool[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
O: Bool[0 0 0 0 0 0 0 0 0 1 0 1 1 0; 0 1 0 1 0 1 0 0 0 0 0 0 0 0]
Guess: Bool[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
Mult: [0, 0]
result_Z: [0]
logic synd: Bool[0]
Decoded!
Syndrome: Bool[1, 1, 0, 0, 0, 0]
Guess: Bool[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
O: Bool[0 0 0 0 0 0 0 0 0 1 0 1 1 0; 0 1 0 1 0 1 0 0 0 0 0 0 0 0]
Guess: Bool[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
Mult: [0, 0]
result_Z: [0]
logic synd: Bool[0]
Decoded!
Syndrome: Bool[0, 0, 0, 0, 0, 0]
Guess: Bool[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
O: Bool[0 0 0 0 0 0 0 0 0 1 0 1 1 0; 0 1 0 1 0 1 0 0 0 0 0 0 0 0]
Guess: Bool[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
Mult: [0, 0]
result_Z: [0]
logic synd: Bool[0]
Decoded!


Syndrome: Bool[0, 1, 0, 0, 0, 0]
Guess: Bool[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
O: Bool[0 0 0 0 0 0 0 0 0 1 0 1 1 0; 0 1 0 1 0 1 0 0 0 0 0 0 0 0]
Guess: Bool[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
Mult: [0, 0]
result_Z: [0]
logic synd: Bool[0]
Decoded!
Syndrome: Bool[0, 1, 1, 0, 0, 0]
Guess: Bool[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
O: Bool[0 0 0 0 0 0 0 0 0 1 0 1 1 0; 0 1 0 1 0 1 0 0 0 0 0 0 0 0]
Guess: Bool[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
Mult: [0, 0]
result_Z: [0]
logic synd: Bool[0]
Decoded!
Syndrome: Bool[0, 0, 0, 0, 0, 0]
Guess: Bool[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
O: Bool[0 0 0 0 0 0 0 0 0 1 0 1 1 0; 0 1 0 1 0 1 0 0 0 0 0 0 0 0]
Guess: Bool[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
Mult: [0, 0]
result_Z: [0]
logic synd: Bool[0]
Decoded!


Syndrome: Bool[0, 0, 0, 0, 0, 0]
Guess: Bool[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
O: Bool[0 0 0 0 0 0 0 0 0 1 0 1 1 0; 0 1 0 1 0 1 0 0 0 0 0 0 0 0]
Guess: Bool[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
Mult: [0, 0]
result_Z: [0]
logic synd: Bool[0]
Decoded!
Syndrome: Bool[0, 0, 0, 0, 1, 0]
Guess: Bool[0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0]
O: Bool[0 0 0 0 0 0 0 0 0 1 0 1 1 0; 0 1 0 1 0 1 0 0 0 0 0 0 0 0]
Guess: Bool[0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0]
Mult: [0, 0]
result_Z: [0]
logic synd: Bool[1]


Syndrome: Bool[0, 0, 0, 0, 0, 0]
Guess: Bool[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
O: Bool[0 0 0 0 0 0 0 0 0 1 0 1 1 0; 0 1 0 1 0 1 0 0 0 0 0 0 0 0]
Guess: Bool[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
Mult: [0, 0]
result_Z: [0]
logic synd: Bool[0]
Decoded!
Syndrome: Bool[1, 1, 0, 0, 0, 0]
Guess: Bool[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
O: Bool[0 0 0 0 0 0 0 0 0 1 0 1 1 0; 0 1 0 1 0 1 0 0 0 0 0 0 0 0]
Guess: Bool[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
Mult: [0, 0]
result_Z: [0]
logic synd: Bool[0]
Decoded!
Syndrome: Bool[0, 0, 0, 0, 0, 0]
Guess: Bool[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
O: Bool[0 0 0 0 0 0 0 0 0 1 0 1 1 0; 0 1 0 1 0 1 0 0 0 0 0 0 0 0]
Guess: Bool[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
Mult: [0, 0]
result_Z: [0]
logic synd: Bool[0]
Decoded!


Syndrome: Bool[0, 0, 0, 0, 0, 0]
Guess: Bool[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
O: Bool[0 0 0 0 0 0 0 0 0 1 0 1 1 0; 0 1 0 1 0 1 0 0 0 0 0 0 0 0]
Guess: Bool[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
Mult: [0, 0]
result_Z: [0]
logic synd: Bool[0]
Decoded!
Syndrome: Bool[0, 0, 0, 0, 0, 1]
Guess: Bool[0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0]
O: Bool[0 0 0 0 0 0 0 0 0 1 0 1 1 0; 0 1 0 1 0 1 0 0 0 0 0 0 0 0]
Guess: Bool[0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0]
Mult: [0, 0]
result_Z: [0]
logic synd: Bool[0]
Decoded!
Syndrome: Bool[0, 1, 1, 0, 1, 1]
Guess: Bool[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0]
O: Bool[0 0 0 0 0 0 0 0 0 1 0 1 1 0; 0 1 0 1 0 1 0 0 0 0 0 0 0 0]
Guess: Bool[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0]
Mult: [1, 0]
result_Z: [0]
logic synd: Bool[0]
Decoded!


Syndrome: Bool[0, 0, 0, 0, 0, 0]
Guess: Bool[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
O: Bool[0 0 0 0 0 0 0 0 0 1 0 1 1 0; 0 1 0 1 0 1 0 0 0 0 0 0 0 0]
Guess: Bool[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
Mult: [0, 0]
result_Z: [0]
logic synd: Bool[0]
Decoded!
Syndrome: Bool[0, 0, 0, 0, 0, 0]
Guess: Bool[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
O: Bool[0 0 0 0 0 0 0 0 0 1 0 1 1 0; 0 1 0 1 0 1 0 0 0 0 0 0 0 0]
Guess: Bool[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
Mult: [0, 0]
result_Z: [0]
logic synd: Bool[0]
Decoded!
Syndrome: Bool[0, 0, 0, 0, 0, 0]
Guess: Bool[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
O: Bool[0 0 0 0 0 0 0 0 0 1 0 1 1 0; 0 1 0 1 0 1 0 0 0 0 0 0 0 0]
Guess: Bool[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
Mult: [0, 0]
result_Z: [0]
logic synd: Bool[0]
Decoded!


Syndrome: Bool[1, 0, 1, 1, 1, 1]
Guess: Bool[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1]
O: Bool[0 0 0 0 0 0 0 0 0 1 0 1 1 0; 0 1 0 1 0 1 0 0 0 0 0 0 0 0]
Guess: Bool[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1]
Mult: [3, 0]
result_Z: [0]
logic synd: Bool[1]
x_error: 

[0.0, 0.005600000000000049, 0.011700000000000044, 0.013399999999999967, 0.02090000000000003, 0.02639999999999998, 0.028200000000000003, 0.031100000000000017, 0.040200000000000014, 0.04200000000000004, 0.04910000000000003, 0.056499999999999995, 0.05800000000000005, 0.06120000000000003, 0.07099999999999995, 0.07440000000000002, 0.07730000000000004, 0.0766, 0.0867, 0.0917, 0.09619999999999995, 0.09509999999999996, 0.10109999999999997, 0.10599999999999998, 0.11080000000000001, 0.11770000000000003, 0.12419999999999998, 0.12529999999999997, 0.12290000000000001, 0.137, 0.13249999999999995, 0.14329999999999998, 0.1432] z_error: [0.0, 0.0041999999999999815, 0.009399999999999964, 0.015199999999999991, 0.022299999999999986, 0.0232, 0.028699999999999948, 0.031299999999999994, 0.04059999999999997, 0.04249999999999998, 0.050899999999999945, 0.0534, 0.05600000000000005, 0.060799999999999965, 0.07010000000000005, 0.06730000000000003, 0.07369999999999999, 0.08099999999999996, 0.0807, 0.0875000000000000

In [3]:
error_rate = 0.1
    
pcm = [1 0 1 0 1 0 1; 0 1 1 0 0 1 1; 0 0 0 1 1 1 1]
num_bits = 7
num_checks = 3
error = [0 0 0 0 0 1 0]
syn = (pcm * error') .% 2
display(syn)

3×1 Matrix{Int64}:
 0
 1
 1

In [4]:
println(pcm)
println(sparse(pcm))

[1 0 1 0 1 0 1; 0 1 1 0 0 1 1; 0 0 0 1 1 1 1]


sparse([1, 2, 1, 2, 3, 1, 3, 2, 3, 1, 2, 3], [1, 2, 3, 3, 4, 5, 5, 6, 6, 7, 7, 7], [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 3, 7)


In [5]:
@testset "LDPCDecoders.jl" begin

    args = (sparse(pcm), sparse(pcm'), syn, 10, fill(error_rate, num_bits), zeros(num_checks, num_bits), zeros(num_checks, num_bits), zeros(num_bits), zeros(num_bits))
    decoded_error, success = syndrome_decode(args...)

    @test decoded_error == vec(error)

    println(decoded_error)

end

[0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]


Test Summary:   | Pass  Total  Time
LDPCDecoders.jl |    1      1  0.6s


Test.DefaultTestSet("LDPCDecoders.jl", Any[], 1, false, false, true, 1.696606319179e9, 1.696606319805e9, false)

In [6]:
bn = 7
b7 = AssembleCSS(Circ2BicycleH(BicycleSetGen(bn), bn));
sb14 = Stabilizer(fill(0x0, 2*bn), GetXTableau(b7), GetZTableau(b7))

stab_to_gf2(sb14)

14×28 Matrix{Bool}:
 1  1  0  1  0  0  0  1  0  0  0  1  0  …  0  0  0  0  0  0  0  0  0  0  0  0
 0  1  1  0  1  0  0  1  1  0  0  0  1     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  1  1  0  1  0  0  1  1  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  1  1  0  1  1  0  1  1  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 1  0  0  0  1  1  0  0  1  0  1  1  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  1  0  0  0  1  1  0  0  1  0  1  1  …  0  0  0  0  0  0  0  0  0  0  0  0
 1  0  1  0  0  0  1  0  0  0  1  0  1     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  1  0  0  0  1  0  0  0  1  0  1
 0  0  0  0  0  0  0  0  0  0  0  0  0     1  0  1  0  0  1  1  0  0  0  1  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     1  1  0  1  0  0  1  1  0  0  0  1
 0  0  0  0  0  0  0  0  0  0  0  0  0  …  0  1  1  0  1  1  0  1  1  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  1  1  0  0  1  0  1  1  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0

In [7]:
# sb14_checks = parity_checks(sb14)
sb14_scirc, _ = naive_syndrome_circuit(sb14)
sb14_ecirc = naive_encoding_circuit(sb14);

In [8]:
f_x_Steane, f_z_Steane = pf_encoding_plot(Steane7())

Syndrome: Bool[0, 0, 0, 0, 0, 0]
Guess: Bool[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
O: Bool[0 0 0 0 0 0 0 0 0 1 0 1 1 0; 0 1 0 1 0 1 0 0 0 0 0 0 0 0]
Guess: Bool[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
Mult: [0, 0]
result_Z: [0]
logic synd: Bool[0]
Decoded!


Syndrome: Bool[0, 0, 0, 0, 0, 0]
Guess: Bool[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
O: Bool[0 0 0 0 0 0 0 0 0 1 0 1 1 0; 0 1 0 1 0 1 0 0 0 0 0 0 0 0]
Guess: Bool[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
Mult: [0, 0]
result_Z: [0]
logic synd: Bool[0]
Decoded!
Syndrome: Bool[0, 0, 0, 0, 0, 0]
Guess: Bool[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
O: Bool[0 0 0 0 0 0 0 0 0 1 0 1 1 0; 0 1 0 1 0 1 0 0 0 0 0 0 0 0]
Guess: Bool[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
Mult: [0, 0]
result_Z: [0]
logic synd: Bool[0]
Decoded!


Syndrome: Bool[0, 0, 0, 0, 0, 0]
Guess: Bool[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
O: Bool[0 0 0 0 0 0 0 0 0 1 0 1 1 0; 0 1 0 1 0 1 0 0 0 0 0 0 0 0]
Guess: Bool[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
Mult: [0, 0]
result_Z: [0]
logic synd: Bool[0]
Decoded!
Syndrome: Bool[0, 0, 0, 0, 0, 0]
Guess: Bool[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
O: Bool[0 0 0 0 0 0 0 0 0 1 0 1 1 0; 0 1 0 1 0 1 0 0 0 0 0 0 0 0]
Guess: Bool[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
Mult: [0, 0]
result_Z: [0]
logic synd: Bool[0]
Decoded!
Syndrome: Bool[0, 0, 0, 0, 0, 0]
Guess: Bool[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
O: Bool[0 0 0 0 0 0 0 0 0 1 0 1 1 0; 0 1 0 1 0 1 0 0 0 0 0 0 0 0]
Guess: Bool[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
Mult: [0, 0]
result_Z: [0]
logic synd: Bool[0]
Decoded!


Syndrome: Bool[0, 0, 0, 0, 0, 0]
Guess: Bool[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
O: Bool[0 0 0 0 0 0 0 0 0 1 0 1 1 0; 0 1 0 1 0 1 0 0 0 0 0 0 0 0]
Guess: Bool[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
Mult: [0, 0]
result_Z: [0]
logic synd: Bool[0]
Decoded!
Syndrome: Bool[0, 0, 0, 0, 0, 0]
Guess: Bool[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
O: Bool[0 0 0 0 0 0 0 0 0 1 0 1 1 0; 0 1 0 1 0 1 0 0 0 0 0 0 0 0]
Guess: Bool[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
Mult: [0, 0]
result_Z: [0]
logic synd: Bool[0]
Decoded!
Syndrome: Bool[0, 0, 0, 0, 0, 0]
Guess: Bool[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
O: Bool[0 0 0 0 0 0 0 0 0 1 0 1 1 0; 0 1 0 1 0 1 0 0 0 0 0 0 0 0]
Guess: Bool[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
Mult: [0, 0]
result_Z: [0]
logic synd: Bool[0]
Decoded!


Syndrome: Bool[0, 0, 0, 0, 0, 0]
Guess: Bool[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
O: Bool[0 0 0 0 0 0 0 0 0 1 0 1 1 0; 0 1 0 1 0 1 0 0 0 0 0 0 0 0]
Guess: Bool[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
Mult: [0, 0]
result_Z: [0]
logic synd: Bool[0]
Decoded!
Syndrome: Bool[0, 0, 0, 0, 0, 0]
Guess: Bool[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
O: Bool[0 0 0 0 0 0 0 0 0 1 0 1 1 0; 0 1 0 1 0 1 0 0 0 0 0 0 0 0]
Guess: Bool[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
Mult: [0, 0]
result_Z: [0]
logic synd: Bool[0]
Decoded!
Syndrome: Bool[1, 1, 0, 1, 1, 0]
Guess: Bool[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0]
O: Bool[0 0 0 0 0 0 0 0 0 1 0 1 1 0; 0 1 0 1 0 1 0 0 0 0 0 0 0 0]
Guess: Bool[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0]
Mult: [1, 0]
result_Z: [0]
logic synd: Bool[1]


Syndrome: Bool[0, 0, 0, 0, 0, 0]
Guess: Bool[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
O: Bool[0 0 0 0 0 0 0 0 0 1 0 1 1 0; 0 1 0 1 0 1 0 0 0 0 0 0 0 0]
Guess: Bool[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
Mult: [0, 0]
result_Z: [0]
logic synd: Bool[0]
Decoded!
Syndrome: Bool[0, 0, 0, 0, 0, 0]
Guess: Bool[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
O: Bool[0 0 0 0 0 0 0 0 0 1 0 1 1 0; 0 1 0 1 0 1 0 0 0 0 0 0 0 0]
Guess: Bool[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
Mult: [0, 0]
result_Z: [0]
logic synd: Bool[0]
Decoded!
Syndrome: Bool[0, 0, 0, 0, 0, 0]
Guess: Bool[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
O: Bool[0 0 0 0 0 0 0 0 0 1 0 1 1 0; 0 1 0 1 0 1 0 0 0 0 0 0 0 0]
Guess: Bool[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
Mult: [0, 0]
result_Z: [0]
logic synd: Bool[0]
Decoded!


Syndrome: Bool[0, 0, 0, 0, 0, 0]
Guess: Bool[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
O: Bool[0 0 0 0 0 0 0 0 0 1 0 1 1 0; 0 1 0 1 0 1 0 0 0 0 0 0 0 0]
Guess: Bool[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
Mult: [0, 0]
result_Z: [0]
logic synd: Bool[0]
Decoded!
Syndrome: Bool[0, 1, 0, 0, 0, 0]
Guess: Bool[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
O: Bool[0 0 0 0 0 0 0 0 0 1 0 1 1 0; 0 1 0 1 0 1 0 0 0 0 0 0 0 0]
Guess: Bool[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
Mult: [0, 0]
result_Z: [0]
logic synd: Bool[0]
Decoded!
Syndrome: Bool[0, 0, 0, 0, 0, 0]
Guess: Bool[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
O: Bool[0 0 0 0 0 0 0 0 0 1 0 1 1 0; 0 1 0 1 0 1 0 0 0 0 0 0 0 0]
Guess: Bool[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
Mult: [0, 0]
result_Z: [0]
logic synd: Bool[0]
Decoded!


Syndrome: Bool[0, 1, 0, 0, 1, 0]
Guess: Bool[0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0]
O: Bool[0 0 0 0 0 0 0 0 0 1 0 1 1 0; 0 1 0 1 0 1 0 0 0 0 0 0 0 0]
Guess: Bool[0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0]
Mult: [0, 0]
result_Z: [0]
logic synd: Bool[1]
Syndrome: Bool[0, 0, 0, 0, 0, 0]
Guess: Bool[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
O: Bool[0 0 0 0 0 0 0 0 0 1 0 1 1 0; 0 1 0 1 0 1 0 0 0 0 0 0 0 0]
Guess: Bool[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
Mult: [0, 0]
result_Z: [0]
logic synd: Bool[0]
Decoded!
Syndrome: Bool[0, 0, 0, 0, 0, 0]
Guess: Bool[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
O: Bool[0 0 0 0 0 0 0 0 0 1 0 1 1 0; 0 1 0 1 0 1 0 0 0 0 0 0 0 0]
Guess: Bool[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
Mult: [0, 0]
result_Z: [0]
logic synd: Bool[0]
Decoded!


Syndrome: Bool[0, 0, 1, 0, 0, 1]
Guess: Bool[0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0]
O: Bool[0 0 0 0 0 0 0 0 0 1 0 1 1 0; 0 1 0 1 0 1 0 0 0 0 0 0 0 0]
Guess: Bool[0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0]
Mult: [0, 0]
result_Z: [0]
logic synd: Bool[0]
Decoded!
Syndrome: Bool[0, 0, 0, 0, 0, 0]
Guess: Bool[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
O: Bool[0 0 0 0 0 0 0 0 0 1 0 1 1 0; 0 1 0 1 0 1 0 0 0 0 0 0 0 0]
Guess: Bool[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
Mult: [0, 0]
result_Z: [0]
logic synd: Bool[0]
Decoded!
Syndrome: Bool[0, 0, 0, 0, 0, 0]
Guess: Bool[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
O: Bool[0 0 0 0 0 0 0 0 0 1 0 1 1 0; 0 1 0 1 0 1 0 0 0 0 0 0 0 0]
Guess: Bool[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
Mult: [0, 0]
result_Z: [0]
logic synd: Bool[0]
Decoded!


Syndrome: Bool[0, 0, 0, 1, 0, 0]
Guess: Bool[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0]
O: Bool[0 0 0 0 0 0 0 0 0 1 0 1 1 0; 0 1 0 1 0 1 0 0 0 0 0 0 0 0]
Guess: Bool[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0]
Mult: [0, 0]
result_Z: [0]
logic synd: Bool[1]
Syndrome: Bool[0, 0, 0, 1, 0, 0]
Guess: Bool[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0]
O: Bool[0 0 0 0 0 0 0 0 0 1 0 1 1 0; 0 1 0 1 0 1 0 0 0 0 0 0 0 0]
Guess: Bool[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0]
Mult: [0, 0]
result_Z: [0]
logic synd: Bool[0]
Decoded!
Syndrome: Bool[0, 0, 0, 0, 0, 0]
Guess: Bool[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
O: Bool[0 0 0 0 0 0 0 0 0 1 0 1 1 0; 0 1 0 1 0 1 0 0 0 0 0 0 0 0]
Guess: Bool[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
Mult: [0, 0]
result_Z: [0]
logic synd: Bool[0]
Decoded!


Syndrome: Bool[0, 0, 0, 0, 0, 0]
Guess: Bool[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
O: Bool[0 0 0 0 0 0 0 0 0 1 0 1 1 0; 0 1 0 1 0 1 0 0 0 0 0 0 0 0]
Guess: Bool[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
Mult: [0, 0]
result_Z: [0]
logic synd: Bool[0]
Decoded!
Syndrome: Bool[0, 0, 0, 0, 1, 0]
Guess: Bool[0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0]
O: Bool[0 0 0 0 0 0 0 0 0 1 0 1 1 0; 0 1 0 1 0 1 0 0 0 0 0 0 0 0]
Guess: Bool[0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0]
Mult: [0, 0]
result_Z: [0]
logic synd: Bool[1]
Syndrome: Bool[0, 0, 0, 0, 0, 0]
Guess: Bool[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
O: Bool[0 0 0 0 0 0 0 0 0 1 0 1 1 0; 0 1 0 1 0 1 0 0 0 0 0 0 0 0]
Guess: Bool[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
Mult: [0, 0]
result_Z: [0]
logic synd: Bool[0]
Decoded!


Syndrome: Bool[0, 0, 0, 0, 0, 0]
Guess: Bool[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
O: Bool[0 0 0 0 0 0 0 0 0 1 0 1 1 0; 0 1 0 1 0 1 0 0 0 0 0 0 0 0]
Guess: Bool[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
Mult: [0, 0]
result_Z: [0]
logic synd: Bool[0]
Decoded!
Syndrome: Bool[0, 0, 0, 1, 1, 0]
Guess: Bool[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0]
O: Bool[0 0 0 0 0 0 0 0 0 1 0 1 1 0; 0 1 0 1 0 1 0 0 0 0 0 0 0 0]
Guess: Bool[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0]
Mult: [1, 0]
result_Z: [0]
logic synd: Bool[1]
Syndrome: Bool[0, 0, 0, 0, 0, 0]
Guess: Bool[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
O: Bool[0 0 0 0 0 0 0 0 0 1 0 1 1 0; 0 1 0 1 0 1 0 0 0 0 0 0 0 0]
Guess: Bool[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
Mult: [0, 0]
result_Z: [0]
logic synd: Bool[0]
Decoded!


x_error: [0.0, 0.005299999999999971, 0.010099999999999998, 0.016900000000000026, 0.01870000000000005, 0.023299999999999987, 0.03049999999999997, 0.03500000000000003, 0.03820000000000001, 0.04049999999999998, 0.051899999999999946, 0.04959999999999998, 0.05940000000000001, 0.062100000000000044, 0.07189999999999996, 0.07010000000000005, 0.07840000000000003, 0.08409999999999995, 0.08179999999999998, 0.08620000000000005, 0.09630000000000005, 0.09660000000000002, 0.10570000000000002, 0.11509999999999998, 0.10829999999999995, 0.11429999999999996, 0.11499999999999999, 0.12429999999999997, 0.1291, 0.1291, 0.12739999999999996, 0.14149999999999996, 0.1461] z_error: [0.0, 0.0044999999999999485, 0.011299999999999977, 0.013700000000000045, 0.018399999999999972, 0.026599999999999957, 0.028900000000000037, 0.03369999999999995, 0.04049999999999998, 0.04590000000000005, 0.0464, 0.055499999999999994, 0.05679999999999996, 0.06289999999999996, 0.06679999999999997, 0.06869999999999998, 0.07289999999999996, 

([0.0, 0.005299999999999971, 0.010099999999999998, 0.016900000000000026, 0.01870000000000005, 0.023299999999999987, 0.03049999999999997, 0.03500000000000003, 0.03820000000000001, 0.04049999999999998  …  0.11509999999999998, 0.10829999999999995, 0.11429999999999996, 0.11499999999999999, 0.12429999999999997, 0.1291, 0.1291, 0.12739999999999996, 0.14149999999999996, 0.1461], [0.0, 0.0044999999999999485, 0.011299999999999977, 0.013700000000000045, 0.018399999999999972, 0.026599999999999957, 0.028900000000000037, 0.03369999999999995, 0.04049999999999998, 0.04590000000000005  …  0.10970000000000002, 0.11499999999999999, 0.11880000000000002, 0.11660000000000004, 0.1269, 0.12819999999999998, 0.13460000000000005, 0.13290000000000002, 0.13849999999999996, 0.1421])

In [23]:
steane7_pc = parity_checks(Steane7())
steane7_scirc, _ = naive_syndrome_circuit(Steane7());
steane7_ecirc = naive_encoding_circuit(Steane7());

In [60]:
evaluate_code_decoder_w_ecirc_pf(steane7_pc, steane7_ecirc, steane7_scirc, 0.02)

Syndrome: Bool[0, 0, 0, 0, 0, 0]
Guess: Bool[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
O: Bool[0 0 0 0 0 0 0 0 0 1 0 1 1 0; 0 1 0 1 0 1 0 0 0 0 0 0 0 0]
Guess: Bool[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
Mult: [0, 0]
result_Z: [0]
logic synd: Bool[0]
Decoded!


(0.037699999999999956, 0.03849999999999998)

In [73]:
sb1412 = vcat(sb14[1:6], sb14[8:13])
sb1412_scirc, _ = naive_syndrome_circuit(sb1412)
sb1412_ecirc = naive_encoding_circuit(sb1412);

In [126]:
evaluate_code_decoder_w_ecirc_pf(sb1412, sb1412_ecirc, sb1412_scirc, 0.2)

Syndrome: Bool[1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1]
Guess: Bool[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
O: Bool[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 1 1 0; 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 1; 1 1 1 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0; 1 1 0 1 0 0 0 0 1 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
Guess: Bool[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
Mult: [0, 0, 0, 0]
result_Z: [0, 0]
logic synd: Bool[1, 0]

(0.5207999999999999, 0.6041000000000001)

In [10]:
A = [0 1 2 3]
B = [4 5 6 7]

1×4 Matrix{Int64}:
 4  5  6  7

In [11]:
hcat(A, B)

1×8 Matrix{Int64}:
 0  1  2  3  4  5  6  7

In [12]:
guess = [0 0 0 0 0 1 0]''
convert(Matrix{Bool}, guess)
# guess = Bool.(guess)

1×7 Matrix{Bool}:
 0  0  0  0  0  1  0

In [13]:
f = fill(0, 7)'
convert(Matrix{Bool}, f)

1×7 Matrix{Bool}:
 0  0  0  0  0  0  0

In [14]:
# guess = convert(Vector{Bool}, guess)
x_mat = convert(Matrix{Bool}, guess'')
z_mat = convert(Matrix{Bool}, fill(0, 7)')
println(x_mat)
println(z_mat)
Stabilizer(fill(0x0, 1), convert(Matrix{Bool}, guess''), convert(Matrix{Bool}, fill(0, 7)'))

Bool[0 0 0 0 0 1 0]
Bool[0 0 0 0 0 0 0]


+ _____X_

In [15]:
float_fill = fill(0.0, 7)
print(typeof(float_fill))
convert(Matrix{Bool}, float_fill')

Vector{Float64}

1×7 Matrix{Bool}:
 0  0  0  0  0  0  0

In [16]:
convert(Vector{Bool}, vcat([0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0]))

14-element Vector{Bool}:
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0